#if !canImport(ObjectiveC)
import XCTest

extension ReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReaderTests = [
        ("testAnyReader", testAnyReader),
        ("testEraseToAnyReader", testEraseToAnyReader),
        ("testFlatMap", testFlatMap),
        ("testFold", testFold),
        ("testMap", testMap),
        ("testMapSuccess", testMapSuccess),
        ("testPullback", testPullback),
        ("testReplaceError", testReplaceError),
        ("testTap", testTap),
        ("testTryMapSuccess", testTryMapSuccess),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReaderTests.__allTests__ReaderTests),
    ]
}
#endif
